"""test

Revision ID: d54ecf0b5c3c
Revises: edade51efbda
Create Date: 2025-12-19 17:55:15.463774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54ecf0b5c3c'
down_revision: Union[str, None] = 'edade51efbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'tipo_gestion')
    op.drop_column('lotes', 'duracion_dias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('duracion_dias', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lotes', sa.Column('tipo_gestion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
