"""test

Revision ID: e85995d6b143
Revises: 95f55a6d091f
Create Date: 2025-12-19 19:13:45.904070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85995d6b143'
down_revision: Union[str, None] = '95f55a6d091f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumos', sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumos', 'fecha_vencimiento')
    # ### end Alembic commands ###
